# Generated by Django 3.2.5 on 2021-07-08 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(db_index=True, default=0)),
                ('list_order', models.IntegerField(db_index=True, default=0)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('LineEdit', 'Line Edit'), ('TextArea', 'Text Area'), ('Select', 'Select'), ('Checkbox', 'Checkbox'), ('Radiobox', 'Radiobox'), ('Email', 'Email'), ('URL', 'URL'), ('Phone', 'Phone'), ('Boolean', 'Boolean'), ('Numeric', 'Numeric'), ('File', 'File'), ('Image', 'Image'), ('Date', 'Date'), ('Time', 'Time'), ('Rating', 'Rating')], max_length=255)),
                ('options_url', models.URLField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('is_required', models.CharField(blank=True, max_length=255, null=True)),
                ('is_visible', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_rules', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('session', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_survey.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advanced_survey.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
