# Generated by Django 3.2.5 on 2021-07-15 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='validation_rules',
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
