# Generated by Django 3.2.5 on 2021-07-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_survey', '0002_auto_20210715_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options_url',
        ),
    ]
